{% set name = "physics-tenpy" %}
{% set version = "1.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 078c2fb5f466370d49761af7d6b887ae633255ce09d1b3f9fd51497584214fac

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py<37]
  skip: true  # [python_impl == 'pypy']

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - scipy                                  # [build_platform != target_platform]
    - pip                                    # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
  host:
    - pip
    - python
    - cython
    - numpy
    - scipy
  run:
    - python
    - {{ pin_compatible('scipy') }}
    - bottleneck
    - pyyaml
    - h5py

test:
  source_files:
    - tests
    - pyproject.toml
  requires:
    - pytest
    - psutil
  imports:
    - tenpy
  commands:
    - pytest -m "not slow" --ignore=tests/test_examples.py tests

about:
  home: https://github.com/tenpy/tenpy
  license: Apache-2.0
  license_file: LICENSE
  license_url: https://www.apache.org/licenses/LICENSE-2.0
  summary: Simulation of quantum many-body systems with tensor networks in Python
  description: |
    "TeNPy is a package of Python code for the simulation of quantum many-body systems with tensor networks.
    Amongst others, it includes codes for the density matrix renormalization group (DMRG) algorithm
    and the time evolving block decimation (TEBD) algorithm based on matrix product states (MPS).
    The minimal dependency is Python, Numpy and Scipy, but it ships with an optional Cython extension to
    reduce the Python overhead in tensor contractions."
  doc_url: https://tenpy.readthedocs.io/
  dev_url: https://github.com/tenpy/tenpy

extra:
  recipe-maintainers:
    - jhauschild
    - Jakob-Unfried
