{% set name = "physics-tenpy" %}
{% set version = "1.0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 8a6ff318844ac57ae2ca893a5b2d4239eccb3ed11ab0863314ea5260510a27ac


# [1] notes on windows builds (28 oct 2025):
#     - There is a known bug affecting `1.15 <= scipy < 1.15.3` on windows.
#       See https://github.com/scipy/scipy/issues/22558
#       We make sure to exclude these scipy versions explicitly
#     - There are unknown bugs somewhere in scipy/numpy, probably the underlying MKL that cause
#       our tests to fail (lanczos does not converge, np.linalg.eigh raises not converged), only
#       on numpy and only for python 3.10 and 3.11 (<3.10 not tested, end of life).
#       This could probably be resolved by carefully excluding package versions, but I dont have
#       capacity to diagnose which versions cause the problems, and I want to publish for 3.14 ASAP

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [python_impl == 'pypy']
  # restrict python version for windows: see note [1] above
  skip: true  # [win and py<312]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    # restrict scipy version for windows: see note [1] above
    - scipy >=1.15.3                         # [build_platform != target_platform and win]
    - scipy                                  # [build_platform != target_platform and not win]
    - pip                                    # [build_platform != target_platform]
    - setuptools                             # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
  host:
    - pip
    - setuptools
    - python
    - cython
    - numpy
    # restrict scipy version for windows: see note [1] above
    - scipy >=1.15.3            # [win]
    - scipy                     # [not win]
  run:
    - python
    # restrict scipy version for windows: see note [1] above
    - scipy >=1.15.3            # [win]
    - scipy                     # [not win]
    - bottleneck
    - pyyaml
    - h5py

test:
  source_files:
    - tests
    - pyproject.toml
  requires:
    - pytest
    - psutil
  imports:
    - tenpy
  commands:
    - pytest -m "not slow" --ignore=tests/test_examples.py tests

about:
  home: https://github.com/tenpy/tenpy
  license: Apache-2.0
  license_file: LICENSE
  license_url: https://www.apache.org/licenses/LICENSE-2.0
  summary: Simulation of quantum many-body systems with tensor networks in Python
  description: |
    "TeNPy is a package of Python code for the simulation of quantum many-body systems with tensor networks.
    Amongst others, it includes codes for the density matrix renormalization group (DMRG) algorithm
    and the time evolving block decimation (TEBD) algorithm based on matrix product states (MPS).
    The minimal dependency is Python, Numpy and Scipy, but it ships with an optional Cython extension to
    reduce the Python overhead in tensor contractions."
  doc_url: https://tenpy.readthedocs.io/
  dev_url: https://github.com/tenpy/tenpy

extra:
  recipe-maintainers:
    - jhauschild
    - Jakob-Unfried
