{% set name = "physics-tenpy" %}
{% set version = "0.8.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2fa6c38cc89b4167f03aaa336860136f54565bf817818b53d15290c1f79359d9

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py<36]
  skip: true  # [python_impl == 'pypy']

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - pip
    - python
    - cython >=0.29
    - numpy >=1.16
    - scipy >=1.2
    - mkl  # [not win]
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy >=1.2
    - mkl  # [not win]
    - libblas * *mkl  # [not win]
    - bottleneck
    - pyyaml
    - h5py

test:
  source_files:
    - tests
    - setup.cfg
  requires:
    - pytest
  imports:
    - tenpy
  commands:
    - pytest -m "not slow" tests

about:
  home: https://github.com/tenpy/tenpy
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: Simulation of quantum many-body systems with tensor networks in Python
  description: |
    "TeNPy is a package of Python code for the simulation of quantum many-body systems with tensor networks.
    Amongst others, it includes codes for the density matrix renormalization group (DMRG) algorithm
    and the time evolving block decimation (TEBD) algorithm based on matrix product states (MPS).
    The minimal dependency is Python, Numpy and Scipy, but it ships with an optional Cython extension to
    reduce the Python overhead in tensor contractions."
  doc_url: https://tenpy.readthedocs.io/
  dev_url: https://github.com/tenpy/tenpy

extra:
  recipe-maintainers:
    - jhauschild
