{% set name = "physics-tenpy" %}
{% set version = "0.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: cdce1da43d13880889da17023f3bd41293b720c93e1a8d3925ba74b6071cef7c

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py<36]
  skip: true  # [python_impl == 'pypy']

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('cxx') }}
  host:
    - pip
    - python
    - cython >=0.29
    - numpy >=1.16
    - scipy >=1.2
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy >=1.2
    - bottleneck
    - pyyaml
    - h5py

test:
  source_files:
    - tests
    - setup.cfg
  requires:
    - pytest
  imports:
    - tenpy
  commands:
    - pytest -m "not slow" tests

about:
  home: https://github.com/tenpy/tenpy
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: Simulation of quantum many-body systems with tensor networks in Python
  description: |
    "TeNPy is a package of Python code for the simulation of quantum many-body systems with tensor networks.
    Amongst others, it includes codes for the density matrix renormalization group (DMRG) algorithm
    and the time evolving block decimation (TEBD) algorithm based on matrix product states (MPS).
    The minimal dependency is Python, Numpy and Scipy, but it ships with an optional Cython extension to
    reduce the Python overhead in tensor contractions."
  doc_url: https://tenpy.readthedocs.io/
  dev_url: https://github.com/tenpy/tenpy

extra:
  recipe-maintainers:
    - jhauschild
